spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
server:
  port: 12000
logging:
  level:
    com:
      wangli:
        gulimall: debug
