spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: mall.com
    port: 6379
server:
  port: 12000
logging:
  level:
    com:
      wangli:
        gulimall: debug