server:
  port: 88
# 应用名称
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        #          后台管理项目路由规则
        - id: admin_route
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            #            作用，将/api/**重写为 /gulimall-admin/**
            - RewritePath=/api/(?<segment>.*),/gulimall-admin/$\{segment}

#前端项目发送请求时前缀都带上 /api
# http://localhost:88/api/captcha.jpg ==> http://localhost:8080/gulimall-admin/captcha.jpg



