server:
  port: 88
# 应用名称
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        #前端项目发送请求时前缀都带上 /api
        #精确的路由规则放前面，不然会被模糊的规则先匹配

        #仓库模块项目路由规则
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            #作用，将/api/**重写为 /gulimall-admin/**
            #          http://localhost:88/api/product/category/list ==>  http://localhost:10000/product/category/list
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #商品模块项目路由规则
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            #作用，将/api/**重写为 /gulimall-admin/**
            #          http://localhost:88/api/product/category/list ==>  http://localhost:10000/product/category/list
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #第三方模块项目路由规则
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            # http://localhost:88/api/thirdparty/oss/policy ==>  http://localhost:30000/oss/policy
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        #会员模块项目路由规则
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            # http://localhost:88/api/thirdparty/oss/policy ==>  http://localhost:30000/oss/policy
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #后台管理项目路由规则
        - id: admin_route
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            # 作用，将/api/**重写为 /gulimall-admin/**
            # http://localhost:88/api/captcha.jpg ==> http://localhost:8080/gulimall-admin/captcha.jpg
            - RewritePath=/api/(?<segment>.*),/gulimall-admin/$\{segment}