spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: leenow
      access-key: xxx
      secret-key: xxx
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        appcode: xxx

  application:
    name: gulimall-third-party
server:
  port: 40000
logging:
  level:
    com.wangli.gulimall.thirdparty: debug