spring:
  application:
    name: gulimall-cart
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: ubuntu2004.wsl
  session:
    store-type: redis
server:
  port: 30000
logging:
  level:
    com.wangli.gulimall.cart: debug
mall:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10
